articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="list"),
    path("<slug:slug>/", views.ArticleDetailView.as_view(), name="detail"),
    path("articles/write/", views.ArticleCreateView.as_view(), name="write"),
    # path("articles/write/", views.article_form_view, name="write"),
    path("articles/edit/<int:pk>/", views.UpdateArticleView.as_view(), name="edit"),
    path("articles/delete/<int:pk>/", views.DeleteArticlesView.as_view(), name="delete")
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # local urls
    path('', include('articles.urls', namespace='articles')),
    path('', include('users.urls', namespace='users')),
    # 3rd urls
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from uuid import uuid4
import os


def path_and_rename(instance, filename):
    upload_to = 'thumbnails/'
    ext = filename.split('.')[-1]
    
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join(upload_to, filename)


class Article(models.Model):
    TYPE_CHOICES = (
        ('Games', 'Jogos'),
        ('Movies', 'Filmes'),
        ('Series', 'Séries'),
        ('Books', 'Livros'),
    )


    slug = models.SlugField(max_length=150, unique=True, verbose_name='URL')
    title = models.CharField('Título', max_length=150, unique=True)
    thumbnail = models.ImageField('Thumbnail', upload_to=path_and_rename, blank=True)
    thumbnail_credits = models.CharField('Autor da imagem', max_length=150, blank=True)
    type = models.CharField('Assunto', max_length=150, choices=TYPE_CHOICES)

    resume = models.CharField('Resumo', max_length=150)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        limit_choices_to={'is_writer': True},
        verbose_name='Autor',
        )
    body = models.TextField('Texto')
    created = models.DateTimeField('Criado', auto_now_add=True)
    updated = models.DateTimeField('Atualizado', auto_now=True)
    # added fields
    is_exclusive = models.BooleanField('Exclusivo', default=False)
    
    class Meta:
        ordering = ("-created",)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"slug": self.slug})
    

articles/forms.py
from django import forms

from .models import Article


class WriteForm(forms.ModelForm):
    # author = forms.ModelChoiceField(choices)
    class Meta:
        model = Article
        fields = (
            'slug', 
            'title', 
            'thumbnail',
            'thumbnail_credits',
            'type',
            'resume', 
            'body', 
            # 'author'
            'is_exclusive',
            ) 

articles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, CreateView, UpdateView
from django.views.generic.edit import DeleteView

from .forms import WriteForm
from .models import Article


@method_decorator(login_required, name='dispatch')
class ArticleCreateView(CreateView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ArticleCreateView, self).dispatch(*args, **kwargs)
    
    model = Article
    template_name = 'articles/write.html'
    success_url = '/'
    success_message = ''
    form_class = WriteForm


    def form_valid(self, form):
        try:
            obj = form.save(commit=False)
            obj.author = self.request.user
            obj.save()
            messages.success(self.request, "Artigo salvo com sucesso!")
            return super().form_valid(form)
        except Exception as e:
            messages.warning(self.request, "Problema ao salvar o artigo!")
            return super(ArticleCreateView, self)
        
    
    # if user not writer attempts access write page 
    def get(self, request, *args, **kwargs):
        if not request.user.is_writer:
            raise Http404("Página não existe!")
        return super(ArticleCreateView, self).get(request, *args, **kwargs)


class ArticleListView(ListView):
    paginate_by = 6
    model = Article


class ArticleDetailView(DetailView):
    model = Article


@method_decorator(login_required, name='dispatch')
class UpdateArticleView(UpdateView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UpdateArticleView, self).dispatch(*args, **kwargs)
    
    model = Article
    template_name = 'articles/edit.html'
    form_class = WriteForm
    
    def get(self, request, *args, **kwargs):
        if not request.user.is_writer:
            raise Http404("Página não existe!")
        
        return super(UpdateArticleView, self).get(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class DeleteArticlesView(DeleteView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DeleteArticlesView, self).dispatch(*args, **kwargs)
    
    model = Article
    template_name = 'articles/delete.html'
    success_url = '/'
    
    def get(self, request, *args, **kwargs):
        if not request.user.is_writer:
            raise Http404("Página não existe!")
        
        return super(DeleteArticlesView, self).get(request, *args, **kwargs)
    

templates/articles/article_detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block jumbotron %}
  {% if article.thumbnail %}
    <img src="/media/{{article.thumbnail}}" class="rounded mx-auto d-block img-fluid" alt="Responsive image">
    <p>Imagem: <em>{{article.thumbnail_credits}}</em></p>
  {% endif %}
{% endblock %}

{% block content %}
          
          <div class="blog-post">
            <h2 class="blog-post-title">{{article.title}}</h2>
            <p class="blog-post-meta">Criado por {{article.author}}</p>
            <p class="blog-post-meta">Atualizado: {{article.updated}}</p>

            <p><em>{{article.resume}}</em></p>
            {% if user.is_writer %}
            {% if article.author.id == user.id %}
              <a href="{% url 'articles:edit' article.id %}">Editar</a>
              - <a href="{% url 'articles:delete' article.id %}">Excluir</a>
              {% endif %}  
            {% endif %}
            <hr>
            {% if user.is_authenticated %}
            <p>
            {{article.body}}
            </p>
            {% elif not article.is_exclusive %}
            <p>
            {{article.body}}
            </p>
            {% else %}
            <p>Artigo Exclusivo para assinantes.</p>
            {% endif %}
          </div>
{% endblock %}

templates/articles/article_list.html
{% extends 'base.html' %}

{% block title %}Blog - Últimas notícias{% endblock %}

{% block jumbotron %}
      {% for article in article_list %}
      {% if forloop.first %}
      <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">{{article.title}}</h1>
          <p class="lead my-3">{{ article.resume }}</p>
          <p class="lead mb-0"><a href="{{ article.get_absolute_url }}" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
      </div>
      {% endif %}
      {% endfor %}
{% endblock %}

{% block content %}
    {% if messages %}
     {% for message in messages %}
      {% if forloop.last %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
      {% endif %}
     {% endfor %}
    {% endif %}
    <div class="row mb-2">
    {% if user.is_authenticated %}
      {% if user.is_writer%}
      <a href="{% url 'articles:write' %}">Escrever</a>
      {% endif %}
    {% endif %}
    {% for article in article_list %}
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">{{article.type}}
                {% if user.is_writer %}
                  {% if article.author.id == user.id %}
                 - <a href="{% url 'articles:edit' article.id %}">Editar</a>
                 - <a href="{% url 'articles:delete' article.id %}">Excluir</a>
                  {% endif %}
                {% endif %}
              </strong>
              <h3 class="mb-0">
                <a class="text-dark" href="{{ article.get_absolute_url }}">{{ article.title|linebreaks|truncatewords:8  }}</a>
              </h3>
              <div class="mb-1 text-muted">{{ article.created }}</div>
              <p class="card-text mb-auto">{{ article.resume|linebreaks|truncatewords:4 }}</p>
            </div>
            {% if article.thumbnail %}
                <img class="card-img-right flex-auto d-none d-md-block thumbnail" src="/media/{{article.thumbnail}}" alt="Card image cap">
            {% else %}
                <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
            {% endif %}
          </div>
        </div>
    {% endfor %}
    </div>
    {% if is_paginated %}
      {% include "pagination.html" with page=page_obj %}
    {% endif %}

{% endblock %}

templates/articles/delete.html
{% extends 'base.html'%}

{% block title %}Editar artigo{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_writer %}
    {% if article.author.id == user.id %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Confirmar</button>
    </form>
    {% else %}
    <p>Você não tem permissão para excluir este artigo.</p>
    {% endif %}       
    {% endif %}
    
{% endblock %}

templates/articles/edit.html
{% extends 'base.html'%}

{% block title %}Editar artigo{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_writer %}
    {% if article.author.id == user.id %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Atualizar</button>
    </form>
    <script type="text/javascript">
        var slug = document.getElementById('id_slug')
        var title = document.getElementById('id_title')
        title.onchange = function() {
            var slug_spaceless = title.value.replace(/\s/g, '-')
            var slug_normalized = slug_spaceless.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
            slug.value = slug_normalized.toLowerCase()
        }
    </script>
    {% else %}
    <p>Você não tem permissão para editar este artigo.</p>
    {% endif %}       
    {% endif %}
    
{% endblock %}

templates/articles/write.html
{% extends 'base.html'%}

{% block title %}Escrever novo artigo{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_writer %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Salvar</button>
    </form>
    <script type="text/javascript">
        var slug = document.getElementById('id_slug')
        var title = document.getElementById('id_title')
        title.onchange = function() {
            var slug_spaceless = title.value.replace(/\s/g, '-')
            var slug_normalized = slug_spaceless.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
            slug.value = slug_normalized.toLowerCase()
        }
    </script>        
    {% endif %}
    
{% endblock %}